# Generated by Django 3.2.13 on 2022-11-05 13:22

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[(base.models.OperationType['AD'], 'addition'), (base.models.OperationType['SU'], 'subtraction'), (base.models.OperationType['MU'], 'multiplication')], max_length=100)),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('slackUsername', models.CharField(default='Creativity_TechGenius777', max_length=50, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
